### ISSUE TITLE
Problems with JRuby support

### ISSUE THREAD

**Issue by buger** [mixpanel/mixpanel-ruby#75] opened 2015-04-07 17:56 UTC
Earlier i found this issue #73  which should be fixed by #74. I dig dipper and found that server return empty bodies because of JRuby bug https://github.com/jruby/jruby/issues/1216#issuecomment-35328206. This bug happens only when you run it in experimental Ruby 2.0 support mode (i had to turn it on because this gem require ruby version >= 2 and fails to install on default JRuby). 

So currently its impossible to make it work with Net:HTTP and latest stable JRuby. Why there were added such script requirement of ruby version >= 2?

**Comment by zyskowsk** [comment] 2015-04-07 20:00
Hey @buger, thanks for finding the root cause of that problem!  We started enforcing ruby version >= 2.0 in the 2.0 version of the gem because we wanted to set a base requirement to be clear that we are developing for ruby 2.0 and up.  Even though our test suite still passes on 1.9.3, we do not want to be supporting a ruby version that is no longer maintained.

I am going to push #74 soon, which should help fix this problem.  If you need better compatibility with JRuby, I might suggest using mixpanel-ruby version 1.4.0 until JRuby catches up to ruby 2.0.

Thanks again for all your help!

**Comment by zyskowsk** [comment] 2015-04-07 21:29
addressed in #77, if you have any further questions about this @buger please reach out again!

**Closed by zyskowsk** 2015-04-07 21:29 UTC
